#
###################################
# Site wide configuration
####################################
#
title: York's blog
email:
description: "York's blog - 分享全端開發技術、架構設計與程式設計心得的個人部落格。"
url: https://linyork.github.io  # GitHub Pages 預設網址
baseurl: ""  # 使用者頁面 (username.github.io) 不需要 baseurl，保持空白
keywords: ["York's blog", "blog", "jekyll", "全端開發", "PHP", "Go", "架構設計"]

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Taipei
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!-- more -->
permalink:         /articles/:year-:month/:title

# 排除不需要處理的檔案和資料夾
exclude:
  - docs/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .bundle/
  - README.md
  - LICENSE.txt
  - upgrade-and-start.bat

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  input: GFM  # GitHub Flavored Markdown
  syntax_highlighter: rouge  # 明確指定語法高亮器

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: York
  avatar: favicon.ico
  job: "A programmer"
  bio: "邁向全端"
  email: "jason945119@gmail.com"
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: "linyork"
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
